import { Item } from '@/lib/types';
import * as itemsRepo from './repo/items';

export const SEED_ITEMS: Omit<Item, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'White Cotton T-Shirt',
    photoUri: 'https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg',
    category: 'top',
    subcategory: 'tee',
    colors: ['#FFFFFF'],
    fabric: 'cotton',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 1,
    seasons: ['spring', 'summer', 'fall'],
    tags: ['casual', 'basic'],
    archived: false,
  },
  {
    name: 'Blue Oxford Shirt',
    photoUri: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
    category: 'top',
    subcategory: 'shirt',
    colors: ['#4A90E2'],
    fabric: 'cotton',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 2,
    seasons: ['spring', 'summer', 'fall'],
    tags: ['smart casual'],
    archived: false,
  },
  {
    name: 'Gray Hoodie',
    photoUri: 'https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg',
    category: 'top',
    subcategory: 'hoodie',
    colors: ['#808080'],
    fabric: 'cotton',
    warmth: 1,
    waterproof: false,
    windproof: false,
    formalLevel: 1,
    seasons: ['fall', 'winter', 'spring'],
    tags: ['casual', 'comfortable'],
    archived: false,
  },
  {
    name: 'Denim Jacket',
    photoUri: 'https://images.pexels.com/photos/1124468/pexels-photo-1124468.jpeg',
    category: 'outerwear',
    subcategory: 'jacket',
    colors: ['#4169E1'],
    fabric: 'denim',
    warmth: 1,
    waterproof: false,
    windproof: true,
    formalLevel: 1,
    seasons: ['spring', 'fall'],
    tags: ['casual'],
    archived: false,
  },
  {
    name: 'Black Trench Coat',
    photoUri: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    category: 'outerwear',
    subcategory: 'coat',
    colors: ['#000000'],
    fabric: 'cotton',
    warmth: 2,
    waterproof: true,
    windproof: true,
    formalLevel: 2,
    seasons: ['fall', 'spring'],
    tags: ['elegant'],
    archived: false,
  },
  {
    name: 'Wool Coat',
    photoUri: 'https://images.pexels.com/photos/3755021/pexels-photo-3755021.jpeg',
    category: 'outerwear',
    subcategory: 'coat',
    colors: ['#654321'],
    fabric: 'wool',
    warmth: 3,
    waterproof: false,
    windproof: true,
    formalLevel: 2,
    seasons: ['winter'],
    tags: ['warm', 'formal'],
    archived: false,
  },
  {
    name: 'Blue Jeans',
    photoUri: 'https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg',
    category: 'bottom',
    subcategory: 'jeans',
    colors: ['#1E3A8A'],
    fabric: 'denim',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 1,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    tags: ['casual', 'versatile'],
    archived: false,
  },
  {
    name: 'Beige Chinos',
    photoUri: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
    category: 'bottom',
    subcategory: 'chinos',
    colors: ['#F5DEB3'],
    fabric: 'cotton',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 2,
    seasons: ['spring', 'summer', 'fall'],
    tags: ['smart casual'],
    archived: false,
  },
  {
    name: 'Khaki Shorts',
    photoUri: 'https://images.pexels.com/photos/1261422/pexels-photo-1261422.jpeg',
    category: 'bottom',
    subcategory: 'shorts',
    colors: ['#C3B091'],
    fabric: 'cotton',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 1,
    seasons: ['summer'],
    tags: ['casual', 'summer'],
    archived: false,
  },
  {
    name: 'White Sneakers',
    photoUri: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg',
    category: 'shoes',
    subcategory: 'sneakers',
    colors: ['#FFFFFF'],
    fabric: 'synthetic',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 1,
    seasons: ['spring', 'summer', 'fall'],
    tags: ['casual', 'comfortable'],
    archived: false,
  },
  {
    name: 'Brown Leather Boots',
    photoUri: 'https://images.pexels.com/photos/1460838/pexels-photo-1460838.jpeg',
    category: 'shoes',
    subcategory: 'boots',
    colors: ['#8B4513'],
    fabric: 'leather',
    warmth: 1,
    waterproof: true,
    windproof: false,
    formalLevel: 2,
    seasons: ['fall', 'winter'],
    tags: ['durable'],
    archived: false,
  },
  {
    name: 'Black Leather Belt',
    photoUri: 'https://images.pexels.com/photos/2562878/pexels-photo-2562878.jpeg',
    category: 'accessory',
    subcategory: 'belt',
    colors: ['#000000'],
    fabric: 'leather',
    warmth: 0,
    waterproof: false,
    windproof: false,
    formalLevel: 2,
    seasons: ['spring', 'summer', 'fall', 'winter'],
    tags: ['accessory'],
    archived: false,
  },
];

export async function seedDatabase(): Promise<void> {
  try {
    const existingItems = await itemsRepo.getAllItems();

    if (existingItems.length > 0) {
      console.log('Database already seeded');
      return;
    }

    for (const seedItem of SEED_ITEMS) {
      const item: Item = {
        ...seedItem,
        id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      };

      await itemsRepo.createItem(item);
    }

    console.log(`Seeded ${SEED_ITEMS.length} items`);
  } catch (error) {
    console.error('Failed to seed database:', error);
  }
}
